# 服务器配置
server:
  port: 8080
  mode: debug  # debug, release

# 数据库配置
database:
  driver: mysql
  host: localhost
  port: 3306
  username: root
  password: your_password
  dbname: family_chef
  charset: utf8mb4
  parse_time: true
  loc: Local
  max_idle_conns: 10
  max_open_conns: 100
  conn_max_lifetime: 3600

# Redis配置
redis:
  host: localhost
  port: 6379
  password: ""
  db: 0
  pool_size: 10

# 微信小程序配置
wechat:
  app_id: your_app_id
  app_secret: your_app_secret
  token: your_token
  encoding_aes_key: your_encoding_aes_key

# JWT配置
jwt:
  secret: your_jwt_secret_key
  expire_hours: 24

# 腾讯云COS配置
cos:
  secret_id: your_secret_id
  secret_key: your_secret_key
  region: ap-beijing
  bucket: your_bucket_name
  domain: your_cos_domain

# 日志配置
log:
  level: info  # debug, info, warn, error
  filename: logs/app.log
  max_size: 100
  max_age: 30
  max_backups: 10

# 文件上传配置
upload:
  max_size: 10485760  # 10MB
  allowed_types: ["jpg", "jpeg", "png", "gif"]
  upload_path: "./uploads" 